name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '38 1 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['swift', '']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Uncomment the following lines if Autobuild fails
      # - name: Manual Build
      #   run: |
      #     # Your build commands here

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

        # Uncomment and customize the queries if needed
        # with:
        #   queries: security-extended,security-and-quality
